name: Display Inputs to Workflow

runs:
  using:  'composite'
  steps:
    - name: Display Inputs on GitHub Summary
      if: ${{ inputs.display_on_github_summary == 'true' }}
      uses: actions/github-script@v6
      with:
        script: |
          const input = ${{ toJSON(github.event.inputs) }}
          let table = [
            [
                { data: 'Input', header: true },
                { data: 'Value', header: true },
            ]
          ];
          for (var key in input) {
            try {
              parsed = JSON.parse(input[key]);
              if(Array.isArray(parsed)) {
                formatted = JSON.parse(input[key]).join('</br>');
                table.push([ key, formatted ])
              } else {
                table.push([ key, input[key] ])
              }
            } 
            catch (e) {
              table.push([ key, input[key] ])
            }
          }
          await core.summary
          .addHeading(`Inputs Provided to Workflow:`)
          .addTable(table)
          .write()